title: Learn LLM
author: li.luo

execute:
  execute_notebooks: "off"

parse:
  myst_enable_extensions:
    - colon_fence

html:
  use_repository_button: true
  use_issues_button: true

repository:
  url: https://github.com/luoli523/learn_llm
  branch: main
